# APP VARS

@base_url = http://localhost:8080
@cliente_id = 123

###

GET {{base_url}}/clientes

###

GET {{base_url}}/clientes/{{cliente_id}}

###

POST {{base_url}}/clientes
Content-Type: application/json

{
    "nome": "Paulo Afonso",
    "email": "paulo@email.com",
    "telefone": "35 9999-0000"
}
 
###

PUT {{base_url}}/clientes/{{cliente_id}}
Content-Type: application/json

{
    "nome": "Paulo Jr",
    "email": "9gfh99@email.com",
    "telefone": "35 9 9999-0000"
}

### 

DELETE {{base_url}}/clientes/{{cliente_id}}
