# APP VARS

@base_url = http://localhost:8080
@entrega_id = 1

GET {{base_url}}/entregas/{{entrega_id}}

###

POST {{base_url}}/entregas
Content-Type: application/json

{
    "cliente_id": 1,
    "taxa": 12.98,
    "nome_destinatario": "Flávia",
    "endereco_destinatario": "Rua José das Couves, 999"
}
